# Generated by Django 4.2 on 2024-06-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_manager', '0002_customuser_groups_customuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
